# Generated by Django 4.1.10 on 2023-10-04 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('w2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPartsID',
            fields=[
                ('USER_UID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Arm_UID', models.CharField(max_length=20)),
                ('Foot_UID', models.CharField(max_length=20)),
                ('Limb_UID', models.CharField(max_length=20)),
                ('Hand_UID', models.CharField(max_length=20)),
                ('TotalCoin', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
