# Generated by Django 4.1.10 on 2023-09-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='運動部位',
            new_name='Part',
        ),
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='關卡名稱',
            new_name='Stage',
        ),
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='總遊玩次數',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='總獲得金幣',
            new_name='TotalCoinObtained',
        ),
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='通關次數',
            new_name='TotalPasses',
        ),
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='總遊玩時間',
            new_name='TotalPlaytime',
        ),
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='username',
            new_name='Username',
        ),
    ]
