# Generated by Django 4.1.10 on 2023-10-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armmetrics',
            name='Arm_UID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='footmetrics',
            name='Foot_UID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='UID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='handmetrics',
            name='Hand_UID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='limbmetrics',
            name='Limb_UID',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
