# Generated by Django 4.1.10 on 2023-10-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('w2', '0002_alter_armmetrics_arm_uid_alter_footmetrics_foot_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='USER_UID',
            field=models.CharField(default=0, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
