# Generated by Django 4.1.10 on 2023-09-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0002_rename_運動部位_userplayhistorytotal_part_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='Total',
            new_name='TotalGamePlay',
        ),
    ]
