# Generated by Django 4.1.10 on 2023-09-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0003_rename_total_userplayhistorytotal_totalgameplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplayhistorytotal',
            old_name='TotalPlaytime',
            new_name='TotalPlaytimes',
        ),
    ]
