# Generated by Django 4.1.10 on 2023-10-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0004_alter_gamerecord_id_alter_gamerecord_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerecord',
            name='ID',
        ),
    ]
