# Generated by Django 4.1.10 on 2023-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0004_rename_totalplaytime_userplayhistorytotal_totalplaytimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Part', models.CharField(max_length=20)),
                ('Stage', models.CharField(max_length=20)),
                ('StartTime', models.CharField(max_length=10)),
                ('EndTime', models.CharField(max_length=10)),
                ('PlayTime', models.CharField(max_length=10)),
                ('NumberOfTimes', models.IntegerField()),
                ('Coins', models.CharField(max_length=10)),
            ],
        ),
    ]
