# Generated by Django 4.1.10 on 2023-10-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0005_remove_gamerecord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerecord',
            name='id',
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
