# Generated by Django 4.1.10 on 2023-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2', '0005_userplayhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplayhistory',
            name='NumberOfTimes',
            field=models.CharField(max_length=20),
        ),
    ]
