from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.signin, name="登入畫面"),
    path('signin', views.signin, name="登入畫面"),
    path('首頁', views.首頁, name="首頁"),
    path('遊戲選擇畫面', views.遊戲選擇畫面, name="遊戲選擇畫面"),
    path('簽到', views.Checkin, name="簽到"),
    path('CheckinSearch', views.CheckinSearch, name="CheckinSearch"),
    path('商店', views.商店, name="商店"),
    path('衣櫥', views.衣櫥, name="衣櫥"),
    path('紀錄', views.MetricsTable, name="紀錄"),
    path('紀錄上肢', views.ArmRecords, name="紀錄上肢"),
    path('紀錄下肢', views.FootRecords, name="紀錄下肢"),
    path('紀錄四肢', views.LimbRecords, name="紀錄四肢"),
    path('紀錄手部', views.HandRecords, name="紀錄手部"),
    path('上肢遊戲畫面1-解說', views.上肢遊戲畫面1解說, name="上肢遊戲畫面1-解說"),
    path('上肢遊戲畫面2-解說', views.上肢遊戲畫面2解說, name="上肢遊戲畫面2-解說"),
    path('上肢遊戲畫面3-解說', views.上肢遊戲畫面3解說, name="上肢遊戲畫面3-解說"),
    path('上肢遊戲畫面4-解說', views.上肢遊戲畫面4解說, name="上肢遊戲畫面4-解說"),
    path('上肢遊戲畫面5-解說', views.上肢遊戲畫面5解說, name="上肢遊戲畫面5-解說"),
    path('上肢遊戲畫面6-解說', views.上肢遊戲畫面6解說, name="上肢遊戲畫面6-解說"),
    path('上肢遊戲畫面7-解說', views.上肢遊戲畫面7解說, name="上肢遊戲畫面7-解說"),
    path('上肢遊戲畫面8-解說', views.上肢遊戲畫面8解說, name="上肢遊戲畫面8-解說"),
    path('上肢遊戲畫面9-解說', views.上肢遊戲畫面9解說, name="上肢遊戲畫面9-解說"),


    path('下肢遊戲畫面1-解說', views.下肢遊戲畫面1解說, name="下肢遊戲畫面1-解說"),
    path('下肢遊戲畫面2-解說', views.下肢遊戲畫面2解說, name="下肢遊戲畫面2-解說"),
    path('下肢遊戲畫面3-解說', views.下肢遊戲畫面3解說, name="下肢遊戲畫面3-解說"),
    path('下肢遊戲畫面4-解說', views.下肢遊戲畫面4解說, name="下肢遊戲畫面4-解說"),
    path('下肢遊戲畫面5-解說', views.下肢遊戲畫面5解說, name="下肢遊戲畫面5-解說"),
    path('下肢遊戲畫面6-解說', views.下肢遊戲畫面6解說, name="下肢遊戲畫面6-解說"),
    path('下肢遊戲畫面7-解說', views.下肢遊戲畫面7解說, name="下肢遊戲畫面7-解說"),
    path('下肢遊戲畫面8-解說', views.下肢遊戲畫面8解說, name="下肢遊戲畫面8-解說"),
    path('下肢遊戲畫面9-解說', views.下肢遊戲畫面9解說, name="下肢遊戲畫面9-解說"),

    path('四肢遊戲畫面1-解說', views.四肢遊戲畫面1解說, name="四肢遊戲畫面1-解說"),
    path('四肢遊戲畫面2-解說', views.四肢遊戲畫面2解說, name="四肢遊戲畫面2-解說"),
    path('四肢遊戲畫面3-解說', views.四肢遊戲畫面3解說, name="四肢遊戲畫面3-解說"),
    path('四肢遊戲畫面4-解說', views.四肢遊戲畫面4解說, name="四肢遊戲畫面4-解說"),
    path('四肢遊戲畫面5-解說', views.四肢遊戲畫面5解說, name="四肢遊戲畫面5-解說"),
    path('四肢遊戲畫面6-解說', views.四肢遊戲畫面6解說, name="四肢遊戲畫面6-解說"),
    path('四肢遊戲畫面7-解說', views.四肢遊戲畫面7解說, name="四肢遊戲畫面7-解說"),
    path('四肢遊戲畫面8-解說', views.四肢遊戲畫面8解說, name="四肢遊戲畫面8-解說"),
    path('四肢遊戲畫面9-解說', views.四肢遊戲畫面9解說, name="四肢遊戲畫面9-解說"),

    path('手部遊戲畫面-解說', views.手部遊戲畫面解說, name="手部遊戲畫面-解說"),
    path('手部遊戲畫面1-解說', views.手部遊戲畫面1解說, name="手部遊戲畫面1-解說"),
    path('手部遊戲畫面2-解說', views.手部遊戲畫面2解說, name="手部遊戲畫面2-解說"),

    path('獎勵關卡-解說', views.獎勵關卡解說, name="獎勵關卡-解說"),


    path('四肢遊戲畫面-解說1', views.四肢遊戲畫面解說1, name="四肢遊戲畫面-解說1"),
    path('四肢遊戲畫面-解說2', views.四肢遊戲畫面解說2, name="四肢遊戲畫面-解說2"),
    path('手部遊戲畫面-解說', views.手部遊戲畫面解說, name="手部遊戲畫面-解說"),
    path('遊戲畫面倒數-上肢', views.遊戲畫面倒數上肢, name="遊戲畫面倒數-上肢"),
    path('遊戲畫面倒數-下肢', views.遊戲畫面倒數下肢, name="遊戲畫面倒數-下肢"),
    path('遊戲畫面倒數-四肢', views.遊戲畫面倒數四肢, name="遊戲畫面倒數-四肢"),
    path('遊戲畫面倒數-手部', views.遊戲畫面倒數手部, name="遊戲畫面倒數-手部"),


    path('遊戲畫面-上肢1/', views.遊戲畫面上肢1, name="遊戲畫面-上肢1"),
    path('遊戲畫面-上肢2/', views.遊戲畫面上肢2, name="遊戲畫面-上肢2"),
    path('遊戲畫面-上肢3/', views.遊戲畫面上肢3, name="遊戲畫面-上肢3"),
    path('遊戲畫面-上肢4/', views.遊戲畫面上肢4, name="遊戲畫面-上肢4"),
    path('遊戲畫面-上肢5/', views.遊戲畫面上肢5, name="遊戲畫面-上肢5"),
    path('遊戲畫面-上肢6/', views.遊戲畫面上肢6, name="遊戲畫面-上肢6"),
    path('遊戲畫面-上肢7/', views.遊戲畫面上肢7, name="遊戲畫面-上肢7"),
    path('遊戲畫面-上肢8/', views.遊戲畫面上肢8, name="遊戲畫面-上肢8"),
    path('遊戲畫面-上肢9/', views.遊戲畫面上肢9, name="遊戲畫面-上肢9"),

    path('遊戲畫面-下肢1/', views.遊戲畫面下肢1, name="遊戲畫面-下肢1"),
    path('遊戲畫面-下肢2/', views.遊戲畫面下肢2, name="遊戲畫面-下肢2"),
    path('遊戲畫面-下肢3/', views.遊戲畫面下肢3, name="遊戲畫面-下肢3"),
    path('遊戲畫面-下肢4/', views.遊戲畫面下肢4, name="遊戲畫面-下肢4"),
    path('遊戲畫面-下肢5/', views.遊戲畫面下肢5, name="遊戲畫面-下肢5"),
    path('遊戲畫面-下肢6/', views.遊戲畫面下肢6, name="遊戲畫面-下肢6"),
    path('遊戲畫面-下肢7/', views.遊戲畫面下肢7, name="遊戲畫面-下肢7"),
    path('遊戲畫面-下肢8/', views.遊戲畫面下肢8, name="遊戲畫面-下肢8"),
    path('遊戲畫面-下肢9/', views.遊戲畫面下肢9, name="遊戲畫面-下肢9"),

    path('遊戲畫面-四肢/', views.遊戲畫面四肢, name="遊戲畫面-四肢"),
    path('遊戲畫面-四肢1/', views.遊戲畫面四肢1, name="遊戲畫面-四肢1"),
    path('遊戲畫面-四肢2/', views.遊戲畫面四肢2, name="遊戲畫面-四肢2"),
    path('遊戲畫面-四肢3/', views.遊戲畫面四肢3, name="遊戲畫面-四肢3"),
    path('遊戲畫面-四肢4/', views.遊戲畫面四肢4, name="遊戲畫面-四肢4"),
    path('遊戲畫面-四肢5/', views.遊戲畫面四肢5, name="遊戲畫面-四肢5"),
    path('遊戲畫面-四肢6/', views.遊戲畫面四肢6, name="遊戲畫面-四肢6"),
    path('遊戲畫面-四肢7/', views.遊戲畫面四肢7, name="遊戲畫面-四肢7"),
    path('遊戲畫面-四肢8/', views.遊戲畫面四肢8, name="遊戲畫面-四肢8"),

    path('遊戲畫面-手部1/', views.遊戲畫面手部1, name="遊戲畫面-手部1"),
    path('遊戲畫面-手部2/', views.遊戲畫面手部2, name="遊戲畫面-手部2"),
    path('遊戲畫面-手部3/', views.遊戲畫面手部3, name="遊戲畫面-手部3"),

    path('遊戲畫面-獎勵關卡/', views.遊戲畫面獎勵關卡, name="遊戲畫面-獎勵關卡"),

    path('遊戲畫面-四肢/', views.遊戲畫面四肢, name="遊戲畫面-四肢"),

    path('signup', views.signup, name="signup"),
    path('home', views.首頁, name="首頁"),
    path('遊戲難度選擇-上肢', views.遊戲難度選擇上肢, name="遊戲難度選擇-上肢"),
    path('遊戲難度選擇-下肢', views.遊戲難度選擇下肢, name="遊戲難度選擇-下肢"),
    path('遊戲難度選擇-四肢', views.遊戲難度選擇四肢, name="遊戲難度選擇-四肢"),
    path('遊戲難度選擇-手部', views.遊戲難度選擇手部, name="遊戲難度選擇-手部"),
    path('遊戲難度選擇-上肢', views.遊戲難度選擇上肢, name="遊戲難度選擇-上肢"),
    path('遊戲難度選擇-下肢', views.遊戲難度選擇下肢, name="遊戲難度選擇-下肢"),
    path('遊戲難度選擇-四肢', views.遊戲難度選擇四肢, name="遊戲難度選擇-四肢"),
    path('遊戲難度選擇-手部', views.遊戲難度選擇手部, name="遊戲難度選擇-手部"),

    path('遊戲地圖一星-上肢', views.遊戲地圖一星上肢, name="遊戲地圖一星-上肢"),
    path('遊戲地圖二星-上肢', views.遊戲地圖二星上肢, name="遊戲地圖二星-上肢"),
    path('遊戲地圖三星-上肢', views.遊戲地圖三星上肢, name="遊戲地圖三星-上肢"),
    path('遊戲地圖一星-下肢', views.遊戲地圖一星下肢, name="遊戲地圖一星-下肢"),
    path('遊戲地圖二星-下肢', views.遊戲地圖二星下肢, name="遊戲地圖二星-下肢"),
    path('遊戲地圖三星-下肢', views.遊戲地圖三星下肢, name="遊戲地圖三星-下肢"),
    path('遊戲地圖一星-四肢', views.遊戲地圖一星四肢, name="遊戲地圖一星-四肢"),
    path('遊戲地圖二星-四肢', views.遊戲地圖二星四肢, name="遊戲地圖二星-四肢"),
    path('遊戲地圖三星-四肢', views.遊戲地圖三星四肢, name="遊戲地圖三星-四肢"),
    path('遊戲地圖一星-手部', views.遊戲地圖一星手部, name="遊戲地圖一星-手部"),
    path('遊戲地圖二星-手部', views.遊戲地圖二星手部, name="遊戲地圖二星-手部"),
    path('遊戲地圖三星-手部', views.遊戲地圖三星手部, name="遊戲地圖三星-手部"),

    path('update_profile/', views.update_user_profile, name='update-profile'),
    path('add_gamerecord/', views.add_gamerecord, name='add_gamerecord'),
    path('update_metrics/<str:user_uid>/<str:play_date>/<str:play_part>/',
         views.update_metrics, name='update_metrics'),
    path('ExportMetricsTableToCSV/', views.ExportMetricsTableToCSV,
         name='ExportMetricsTableToCSV'),
    path('ExportGameRecordsToCSV/', views.ExportGameRecordsToCSV,
         name='ExportGameRecordsToCSV'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]
